// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyBirds.Infrastructure.Database.Contexts;

#nullable disable

namespace MyBirds.Migrations.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250914161140_v7_add_fullpath_to_photo")]
    partial class v7_add_fullpath_to_photo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyBirds.Domain.Birds.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("FullPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFavourite")
                        .HasColumnType("bit");

                    b.Property<bool>("IsStarred")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_Photo");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Photo_Name");

                    b.HasIndex("SpeciesId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("MyBirds.Domain.Birds.Species", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GenusId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ScientificName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id")
                        .HasName("PK_Species");

                    b.HasIndex("GenusId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Species_Name");

                    b.HasIndex("ScientificName")
                        .IsUnique()
                        .HasDatabaseName("IX_Species_ScientificName");

                    b.ToTable("Species");
                });

            modelBuilder.Entity("MyBirds.Domain.Classifications.Family", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_Family");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Family_Name");

                    b.HasIndex("OrderId");

                    b.ToTable("Families");
                });

            modelBuilder.Entity("MyBirds.Domain.Classifications.Genus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FamilyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id")
                        .HasName("PK_Genus");

                    b.HasIndex("FamilyId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Genus_Name");

                    b.ToTable("Genera");
                });

            modelBuilder.Entity("MyBirds.Domain.Classifications.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id")
                        .HasName("PK_Order");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Order_Name");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("MyBirds.Domain.Birds.Photo", b =>
                {
                    b.HasOne("MyBirds.Domain.Birds.Species", "Species")
                        .WithMany("Photos")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Species_Photo");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("MyBirds.Domain.Birds.Species", b =>
                {
                    b.HasOne("MyBirds.Domain.Classifications.Genus", "Genus")
                        .WithMany("Species")
                        .HasForeignKey("GenusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Genus_Species");

                    b.Navigation("Genus");
                });

            modelBuilder.Entity("MyBirds.Domain.Classifications.Family", b =>
                {
                    b.HasOne("MyBirds.Domain.Classifications.Order", "Order")
                        .WithMany("Families")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Order_Family");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("MyBirds.Domain.Classifications.Genus", b =>
                {
                    b.HasOne("MyBirds.Domain.Classifications.Family", "Family")
                        .WithMany("Genera")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Family_Genus");

                    b.Navigation("Family");
                });

            modelBuilder.Entity("MyBirds.Domain.Birds.Species", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("MyBirds.Domain.Classifications.Family", b =>
                {
                    b.Navigation("Genera");
                });

            modelBuilder.Entity("MyBirds.Domain.Classifications.Genus", b =>
                {
                    b.Navigation("Species");
                });

            modelBuilder.Entity("MyBirds.Domain.Classifications.Order", b =>
                {
                    b.Navigation("Families");
                });
#pragma warning restore 612, 618
        }
    }
}
